name: GitHub Pages

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install, build, and generate documentation
      run: |
        npm ci
        npm run build
        touch ./doc/.nojekyll
        sed -i '/\/dist/d' .gitignore
        echo "regex-coordinates.leifgehrmann.com" >> ./doc/CNAME
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.6.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./dist
      with:
        forceOrphan: true
